### ISSUE TITLE
There are no executables here 🤷‍♂️

### ISSUE THREAD

**Issue by Voyz** [huggingface/ML-Agents-Training-Executables#1]
It would be fantastic if these were shared 👍 Or if there's a different place we can find these, please leave the link to it. Thanks!

**Comment by simoninithomas** [comment]
Hey there 👋 the executables are here: https://drive.google.com/drive/folders/1HrvHNRLCKwQRWv-JkhhMPTHCwu_iHxZj

But yes we plan in the future to not share them directly.
